
import { GoogleGenAI, Modality } from "@google/genai";
import type { GroundingLink } from '../types';

if (!process.env.API_KEY) {
  throw new Error("API_KEY environment variable is not set");
}

const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

function dataUrlToBlob(dataUrl: string): { data: string, mimeType: string } {
    const [header, base64Data] = dataUrl.split(',');
    const mimeType = header.match(/:(.*?);/)?.[1] || 'image/png';
    return { data: base64Data, mimeType };
}

export const reimagineImage = async (base64ImageData: string, prompt: string): Promise<string> => {
  const { data, mimeType } = dataUrlToBlob(base64ImageData);

  const response = await ai.models.generateContent({
    model: 'gemini-2.5-flash-image',
    contents: {
      parts: [
        { inlineData: { data, mimeType } },
        { text: prompt },
      ],
    },
    config: {
      responseModalities: [Modality.IMAGE],
    },
  });

  for (const part of response.candidates?.[0]?.content?.parts || []) {
    if (part.inlineData) {
      return `data:${part.inlineData.mimeType};base64,${part.inlineData.data}`;
    }
  }
  throw new Error("No image generated by the API.");
};

export const findShoppableLinks = async (prompt: string): Promise<{ text: string, links: GroundingLink[] }> => {
    const response = await ai.models.generateContent({
        model: "gemini-2.5-flash",
        contents: `Find shoppable links for the following item: ${prompt}. Provide a brief description and then the links.`,
        config: {
            tools: [{ googleSearch: {} }],
        },
    });

    const text = response.text;
    const groundingChunks = response.candidates?.[0]?.groundingMetadata?.groundingChunks || [];
    
    const links: GroundingLink[] = groundingChunks
        .map(chunk => chunk.web)
        .filter((web): web is { uri: string, title: string } => !!web && !!web.uri && !!web.title)
        .map(web => ({ uri: web.uri, title: web.title }));

    return { text, links };
};
